baseurl = "/"
languageCode = "en-us"
title = "Simon Rolph"
theme = "hugo-simon"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/about/cv"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Field Notes"
    url = "/categories/R/"
    weight = 2


[params]
    description = "Simon Rolph - Quantitative Ecologist, SciComm-er and Train Enthusiast"
    custom_css = ["css/theme-override.css"]
