baseurl = "/simonrolph"
languageCode = "en-us"
title = "Simon Rolph"
theme = "hugo-simon"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About My Research"
    url = "/about/PhD-overview"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/about/cv"
    weight = 7
#[[menu.main]]
#    name = "Blog"
#    url = "/blog_post"
#    weight = 6
#[[menu.main]]
#    name = "Field Notes"
#    url = "/field_note"
#    weight = 5
#[[menu.main]]
#    name = "Code Notes"
#    url = "/code_note"
#    weight = 4

[params]
    description = "Simon Rolph - Quantitative Ecologist, SciComm-er and Train Enthusiast"
    custom_css = ["css/theme-override.css"]
