---
title: "Simon Rolph - CV"
categories: About me
---

## Personal Statement

## Education

#### 2016 - Present, University of Sheffield
**PhD student at the University of Sheffield, Department of Animal and Plant science.** 
Primary supervisor: Dr Dylan Childs, with supporting supervisors; Dr Rob Salguero-Gómez, Dr Jonathan Potts and Proffessor Rob Freckleton. President of the Animal and Plant Sciences Department PostGrad Soceity (June 2017-current)

#### 2013-2016, University of Exeter
**BSc (Hons) in Conservation Biology and Ecology at University of Exeter (Penryn Campus) - 1st Class.**
Third year modules: Tenerife Field Course, Mathematical Biology and Ecology, Ecology and Evolution of Disease, Marine Spatial Ecology. Second year modules: Iceland Field Course, Mathematics of the Environment, Analysis of Biological Data, Biodiversity and Conservation, Biology of Aquatic Vertebrates, Ecological Consultancy.

## Conferences, Courses and Working Groups

<table class="table">
<tbody>

<tr>
<td>
December 2017
</td>
<td>
**Ecology Across Borders** (British Ecological Soceity Annual Meeting) in Ghent. I presented a poster on my work on simulated plant life history strategies as a tool to guide comparative research of matrix population models.
</td>
</tr>

<tr>
<td>
March 2017
</td>
<td>
**Matrix Approaches Health Demography** (2 weeks), taught by Hal Caswell at the Max Planck Institute for Demographic Research. This course introduced methods based on Markov chains, Markov chains with rewards, multistate matrix models, and matrix calculus.
</td>
</tr>

<tr>
<td>
December 2016
</td>
<td>
**British Ecological Society Annual Meeting** in Liverpool. Presented an outreach poster about the COMPADRE Plant Matrix Database and COMADRE Plant Matrix Dabase. A version of this poster is available [here](https://compadredb.files.wordpress.com/2014/10/compadreposter-english.pdf).
</td>
</tr>

<tr>
<td>
October 2016
</td>
<td>
**Integral Projection Models: Demography in a Continuous World** (1 week), Barcelona. Taught by Tim Coulson, Eelke Jongejans, Rob Salguero-Gómez and Maria Paniw. This course was coordinated by [Transmitting science](https://www.transmittingscience.org/). This course taught basic and advanced applications of IPMs to construct IPMs and estimate a number of important population rates including sensitivity analyses, life table response experiments, stochastic projections and times to local extinction.
</td>
</tr>

<tr>
<td>
June 2016
</td>
<td>
International **Demography Working Group** (1 week), hosted by Prof. Dave Hodgson at the University of Exeter. Other attendees were population ecologists from around the world: Elizabeth Crone, Drew Tyre, Judy Che-Castaldo, Iain Stott, Rob Salguero-Gómez, Owen Jones, Ruth Archer, Yvonne Buckley.
</td>
</tr>

</tbody>
</table>

Other short courses: 

 * **Be Better Than Boring Bullet Points** (February 2018). This day course explored the tricks, tips and techniques of great presenters. Taught by [Steve Hutchinson](http://www.hutchinsontraining.com/).
 * **Foundations for Effective Scientific Writing** (January 2017). This 4-day workshop introduced the core writing skills that will be required in graduate studies, looking at the primary challenge of achieving clarity when presenting complex scientific information. Taught by [Iain Patten](http://iainpatten.com/).


## Teaching

<table class="table">
<tbody>
<tr>
<td>
Spring 2018
</td>
<td>
Teaching asssitant for a first-year undergraduate **R and statistics** course taught by Dr Bethan Hindle. This course introduced undergraduates to the basics of command-line data analysis and data visualisation.
</td>
</tr>

<tr>
<td>
Autumn 2017
</td>
<td>
Teaching asssitant for a second-year undergraduate **R and statistics** course taught by Dr Dylan Childs.
</td>
</tr>

<tr>
<td>
Spring 2017
</td>
<td>
Facilitator for a small tutorial group module titled '**Breaking Boundaries**': an interdisciplinary undergraduate module designed to provide experience in researching an issue, forming an argument and presenting it in a debate. My assigned groups were given the topic: will true artificial intelligence be possible winthin 20 years?
</td>
</tr>

</tbody>
</table>


## Internships

<table class="table">
<tbody>

<tr>
<td>
Summer 2016
</td>
<td>
Internship with Prof. David Hodgson’s research group working with the **COMPADRE Plant Matrix Database** (10 weeks). My main role was data input, processing and error checking of matrix population models from scientific literature into COMPADRE database. I also worked on the front-end development of a web application for the COMPADRE database using Python, Javascript and HTML.
</td>
</tr>

</tbody>
</table>




## Volunteering

<table class="table">
<tbody>
<tr>
<td>
2014
</td>
<td>
Part-time lead volunteer at Falmouth Aquarium.
</td>
</tr>

<tr>
<td>
2013
</td>
<td>
Four month full-time lead volunteer bottlenose dolphin research assistant at Cardigan Bay Marine Wildlife Centre.
</td>
</tr>

<tr>
<td>
2010-2013
</td>
<td>
Practical conservation work party volunteer and Ecology Groups office-based volunteer with Wildlife Trust for Bedfordshire, Cambridgeshire and Northamptonshire.
</td>
</tr>

</tbody>
</table>


